-- Seed curated names for the four races covered in Phase 1.
-- More races/names can be added later via a plain migration -- adding a
-- race is a one-line change to the CHECK constraint plus a seed insert,
-- by design (see docs/ARCHITECTURE.md, "Why not native Postgres enums").

INSERT INTO names (display_name, normalized_name, race, gender, source, status) VALUES
    ('Elandril', 'elandril', 'ELF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Thalorion', 'thalorion', 'ELF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Varendil', 'varendil', 'ELF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Caelith', 'caelith', 'ELF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Ithrandor', 'ithrandor', 'ELF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Selwyn', 'selwyn', 'ELF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Aelriana', 'aelriana', 'ELF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Sylvethra', 'sylvethra', 'ELF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Miralei', 'miralei', 'ELF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Thessaly', 'thessaly', 'ELF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Nimwen', 'nimwen', 'ELF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Ealasaid', 'ealasaid', 'ELF', 'FEMININE', 'CURATED', 'ACTIVE'),

    ('Borgrim', 'borgrim', 'DWARF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Thrandik', 'thrandik', 'DWARF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Ulfgar', 'ulfgar', 'DWARF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Dorlin Ironfoot', 'dorlin ironfoot', 'DWARF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Kazrik Stonebeard', 'kazrik stonebeard', 'DWARF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Bruntok', 'bruntok', 'DWARF', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Brenna Deepdelver', 'brenna deepdelver', 'DWARF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Torga Battleaxe', 'torga battleaxe', 'DWARF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Helda Ironfist', 'helda ironfist', 'DWARF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Vondra', 'vondra', 'DWARF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Ragna Coalheart', 'ragna coalheart', 'DWARF', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Sigrun', 'sigrun', 'DWARF', 'FEMININE', 'CURATED', 'ACTIVE'),

    ('Eamon Blackwood', 'eamon blackwood', 'HUMAN', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Roderick Vane', 'roderick vane', 'HUMAN', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Corwin Ashdale', 'corwin ashdale', 'HUMAN', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Bastian Thorne', 'bastian thorne', 'HUMAN', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Griffin Marlowe', 'griffin marlowe', 'HUMAN', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Alaric Voss', 'alaric voss', 'HUMAN', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Isolde Ravensworth', 'isolde ravensworth', 'HUMAN', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Marguerite Thorne', 'marguerite thorne', 'HUMAN', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Wren Ashford', 'wren ashford', 'HUMAN', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Seraphina Vane', 'seraphina vane', 'HUMAN', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Odalys Marlowe', 'odalys marlowe', 'HUMAN', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Fenella Brightwater', 'fenella brightwater', 'HUMAN', 'FEMININE', 'CURATED', 'ACTIVE'),

    ('Pip Underhill', 'pip underhill', 'HALFLING', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Wendell Goodbarrel', 'wendell goodbarrel', 'HALFLING', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Milo Brambleroot', 'milo brambleroot', 'HALFLING', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Tobin Fairweather', 'tobin fairweather', 'HALFLING', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Alfrik Meadowlark', 'alfrik meadowlark', 'HALFLING', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Corin Thistlewood', 'corin thistlewood', 'HALFLING', 'MASCULINE', 'CURATED', 'ACTIVE'),
    ('Rosie Underbough', 'rosie underbough', 'HALFLING', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Pearl Goodbarrel', 'pearl goodbarrel', 'HALFLING', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Marigold Brushgather', 'marigold brushgather', 'HALFLING', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Tansy Fairweather', 'tansy fairweather', 'HALFLING', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Poppy Thistlewood', 'poppy thistlewood', 'HALFLING', 'FEMININE', 'CURATED', 'ACTIVE'),
    ('Willow Meadowlark', 'willow meadowlark', 'HALFLING', 'FEMININE', 'CURATED', 'ACTIVE');
